#! /usr/bin/python3

import sys 
sys.path.append("./autom")

from autom import *
# import autom
    
p = Project("TestProject","0.0.0")

if build_mode == ProjectFileType.GN:
    print("Building For GN")
elif build_mode == ProjectFileType.CMAKE:
    print("Building For CMake")

# TEST_VAR = 1

# configure("./Test.txt.in","./Test.txt",globals())

myLib = Library("TestLib",source_files=["./TestLib.cpp"],dependencies=[],output_dir="bin",shared=False)

test = Executable("TestExec",source_files=["./test.cpp"],dependencies=[],output_dir="bin")


p.add_targets(list=[test,myLib])

export = p


