#! /usr/bin/python3

if build_mode == ProjectFileType.GN:
    print("Building For GN")
elif build_mode == ProjectFileType.CMAKE:
    print("Building For CMake")

TEST_VAR = 1

configure("./Test.txt.in","./Test.txt",globals())

myLib = Library("TestLib",source_files=["./TestLib.cpp"],dependencies=[],output_dir="./bin",shared=False)

test = Executable("TestExec",source_files=["./test.cpp"],dependencies=[],output_dir="./bin")

export = [myLib,test]



